site_name: Test docs
site_description: 'A docs test'
site_author: 'Defenestration'
docs_dir: docs/
repo_name: 'defenestration/mkdocs'
repo_url: 'https://github.com/defenestration/mkdocs'
nav:
    - Home: index.md
    - About: about.md
theme:
  name: 'material'
  nav_style: dark
plugins:
- search
- tags: