site_name: Test docs
site_description: 'A docs test'
site_author: 'Defenestration'
docs_dir: docs/
repo_name: 'defenestration/mkdocs'
repo_url: 'https://github.com/defenestration/mkdocs'
#nav:
#    - Home: index.md
#    - About: about.md
theme:
  name: material
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      # accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      # accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.top
plugins:
- search
# automatically link 'bare' urls
markdown_extensions:
- pymdownx.magiclink

